### ISSUE TITLE
Choose a name and document which properties are written/read by formats

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#150]
Properties are being used more and more, and the names of existing properties have no consistency right now. On the top of my head, we have 

- Atomic properties: is_hetatm, 
- Frame properties: name (for molecular name), various properties from the SDF format
- Residue properties (#148): chainid, chainname, chainindex

We should pick a consistent scheme for naming properties (maybe something like `<FORMAT>_property`, i.e. `PDB_is_hetatm`, `MMTF_chainid`). Do you have any idea for this?

And we should document which properties are used (set/read) by each format.

Pinging @frodofine and @pgbarletta on this, as you are the main users of properties !

**Comment by pgbarletta** [comment]
Assigning formats to properties could be problematic since formats share some properties (eg: chainid between MMTF and PDB). 

The `Property` class is used by both the Chemfiles library and the users, something which is not rare, but I think the problem lies in the fact that conventional users (those that haven't added a new `Property` object to her/his atoms or frames) are also obliged to know about the `Property` class to get basic info like, whether an atom is a heteroatom or not.

Given the abstract and vague nature of the "Property" class, I don't think the conventional user needs to know that these unrelated pieces of information (if an atom is a heteroatom or the ID of a polypeptide chain) are actually implemented in the same way. If I recall correctly, before calling this class `Property`, we were debating if we should call it `Information` or something else; so, it's just that, info.

I think that, given the current state of the code, the easiest way to do this would be to enclose the `get()` function within a function with a more informative name. And then, that function would call the `get()` function with the appropriate string that specifies which piece of information is being queried.
Would be something like this:
```
auto atom = traj("sample.pdb").read().topology()[0];
// Is this an hetero atom?
bool het = atom.is_hetatm()
```
And on the Chemfiles side, inside `Atom.cpp`:
```
bool is_hetatm() {
    return properties_.get("is_hetatm").value_or(false).as_bool())
}
```

Therefore, only users that have constructed their own properties will have to deal with a naming scheme, but that naming scheme would be their naming scheme!
Hope this makes sense.

**Comment by Luthaf** [comment]
> Assigning formats to properties could be problematic since formats share some properties (eg: chainid between MMTF and PDB).

True, I did not thought of this.

> I think that, given the current state of the code, the easiest way to do this would be to enclose the get() function within a function with a more informative name. And then, that function would call the get() function with the appropriate string that specifies which piece of information is being queried.

To me, this defeat one of the goals of having properties: not cluttering the API. My initial idea with properties was to add a way to store various additional data for frame/atoms without adding a new function for every property. 

If we did not have properties, we would need to add new functions for molecule name, chainame, chainid, chainindex, *etc.*. Even without thinking of mirroring every single function to the C API, this would add quite a bit of complexity when using the code. (For an example of having new functions for every property, the OpenBabel API has functions [to check](http://openbabel.org/api/2.3/classOpenBabel_1_1OBAtom.shtml#ab633bc0f8f40dfcedf42940ab8a5316c) if an atom is an hydrogen, or a carbon, or a sulphur, or ...)

Also properties does not always map to a single name eveytime: if my understanding is correct, the SDF format support any name for property, even something like `FOO_BAR04435` that can not be mapped to a function.

At the same time I agree that for simple properties such as `is_hetatm`, it could be nice to have simpler wrapper. But then, where should we draw the line between what is only accessible as a property and what get a function? I think that a good way to do this is to only create a functions if the corresponding data is used by more than n formats (n being somewhere between 2 and 5)

**Comment by frodofine** [comment]
Luthaf beat me to this, but here is my take:

I do not think enclosing `get()` within function calls is practical as then we should need to make CAPI calls for all of these properties and possibly port them over to Python/Rust/Fortran/Julia/whatever. The beauty, in my opinion, of properties is that they are generic and the addition of a property (IE chainid, atom type, hyperpolarizability, etc) does not require additional API hooks. A client library can manage properties itself this way and it is up to the developer of that library to check whether a given property is set, and assign it an appropriate default if not.

Documenting the properties set by a given format is a great idea, but this should not be done in a format dependent manner. Some properties, like chainid and chainname are shared between formats, others are not. What is the meaning of `hetatm` in an `xyz` file?

Maybe it is best to create a hierarchy of properties. For example, if `is_protein` is set, then the presence of `chainid` is guaranteed.  Since different formats are commonly used for different applications, we could assign these hierarchies based on format (`SDF` for example will never assign a chainid).

There is one major flaw here, however. Different structure sources are not equal. PubChem, for example, assigns a myriad of properties to the `SDF` structures they provide, ranging from experimental observations to quantum mechanical properties. RCSB, however, only provides topological information in their `SDF`s however.  So maybe instead of format based properties, we could have provider based properties. I'm not sure about how to implement this, however.  One solution is to save all properties and let the client decide which ones they/don't need, but that seems error prone - especially since there is no way of knowing the names of all the properties in a `Frame` or `Atom`.

Maybe a first step is enabling the client library the ability to iterate through the `Property` names?

**Comment by pgbarletta** [comment]
OK, fair enough, I certainly don't want Chemfiles to go down the OpenBabel road.

I've checked the names of some properties and they all seem intuitive to me and there isn't so many of them, so I can't think of an original naming scheme.

Then, I think documentation is the way to go for now.
Something like a "Default Properties" section, listing them and showing an example code line for each one, like
`get("is_hetatm").value_or(false).as_bool())`

I also like this idea:
> Maybe a first step is enabling the client library the ability to iterate through the Property names?

Changes in the implementation beyond that seem a tad too much to solve this issue.

**Comment by Luthaf** [comment]
> Maybe a first step is enabling the client library the ability to iterate through the Property names?

Yes, this sounds good!

> Maybe it is best to create a hierarchy of properties. For example, if is_protein is set, then the presence of chainid is guaranteed. Since different formats are commonly used for different applications, we could assign these hierarchies based on format (SDF for example will never assign a chainid).

This will be hard to do, as some files might not have all the properties required by a given standard set. For example the PDB format is used outside of the RCSB database, and a lot of files around will miss this kind of data. And giving provider-dependent guarantees on the properties will event be harder.

> Something like a "Default Properties" section, listing them and showing an example code line for each one, like

This would be a nice way to present them, together with a list of formats using the property. Concerning code examples, it might be better to have a "How to use properties" instead, that show some examples of working with them.

**Comment by frodofine** [comment]
> This will be hard to do, as some files might not have all the properties required by a given standard set. For example the PDB format is used outside of the RCSB database, and a lot of files around will miss this kind of data. And giving provider-dependent guarantees on the properties will event be harder.

In the end, I do not think it is the job of Chemfiles to provide this information/determine these properties - instead this is the job of the client library. I currently use Chemfiles to read a format, obtain the topology of the molecules in a file, and do statistics on these molecules that is independent of Chemfiles. I save some properties to the `Atom` and `Residue` classes, but I work with these properties exclusively (and do not expect them to be saved with topology information). If a given property is missing, I either calculate it or throw an error.

Fortunately, this approach places less burden on the end user than other software in my field so throwing an error when the user does not provide me with the required information is acceptable.

My use of properties is different than that of others, and I would expect the developers of other client libraries to understand properties before they begin development.

> OK, fair enough, I certainly don't want Chemfiles to go down the OpenBabel road.

My advisor would kill me if I used OpenBabel (or anything resembling its complexity) :smile: , so let's avoid this at all costs!

**Comment by pgbarletta** [comment]
Sorry for taking so long, but I keep wondering what would be the best way to iterate over all properties available for an `Atom` / `Residue` / `Frame`.

1_
I could expose the standard iterators of the std::unordered_map from the Property class:
```
  std::unordered_map<std::string, Property>::const_iterator cbegin() const {
    return data_.cbegin();
  }

  std::unordered_map<std::string, Property>::const_iterator cend() const {
    return data_.cend();
  }
```
And then do the same for the classes that own a `Property` object:
```
  std::unordered_map<std::string, Property>::const_iterator  properties_begin() const {
    auto start =  properties_.cbegin();
    auto end =  properties_.cend();

    if (start == end) {
    // Warn the user there are no properties for this object?
       return end;
   } else {
       return start;
  }

  std::unordered_map<std::string, Property>::const_iterator properties_end() const {
    return properties_.cend();
  }
```
But this would be too C++ specific and not amenable to binding (does FORTRAN even have pointers?).

2_
`Atom` / `Residue` / `Frame`  having a `get_each()` method that returns a (name_of_the_property, property) pair (that is, a `std::pair<std::string, Property>`) each time it gets called. This would imply adding an iterator to the `Property` class pointing to the current pair:
```
std::unordered_map<std::string, Property>::const_iterator cursor = data_.cbegin();
```
Along with a new method to expose it while at the same time "circulating" it:
```
/// Get the cursor iterator for the properties.
  std::unordered_map<std::string, Property>::const_iterator get_cursor() {
    if (cursor == data_.cend()) {
      cursor = data_.cbegin();
      return cursor;
    } else {
      return (cursor++);
    }
  }
```
And a new method inside each property-holding-class to output this pair:
```
std::pair<std::string, Property> Atom::get_each() {
  return *properties_.get_cursor();
}
```

3_
`Atom` / `Residue` / `Frame`  having a `get_all()` method to return all properties (by value?) in some form of structure.

4_
The actual solution, that I can't think of.

**Comment by Luthaf** [comment]
Yeah, for C++, using iterators seems good. 

For the C interface, I would use something adapted from OpenMM: have a function returning a `char**` containing the list of properties in a CHFL_FRAME / CHFL_ATOM / CHFL_RESIDUE (like how main takes a `char**`). The main choice will be either to have two functions (one for getting the number of properties, and a second one to set a pre-allocated `char**` provided by the user), or a single one, returning both the number of properties and allocating the `char**`. In the first case, the user is responsible for allocating and `free`-ing the memory, in the second case the user only need to free the memory.

In pseudo code, something like this:

```c
// two functions
chfl_status chfl_atom_properties_count(CHFL_ATOM* atom, uint64_t* count);
chfl_status chfl_atom_properties_names(CHFL_ATOM* atom, char** names);

// single function
chfl_status chfl_atom_properties_names(CHFL_ATOM* atom, uint64_t* count, char*** names);
```

In both cases, I would set the actual names (`char*`) to point to the `std::string` in the property map, as they should live as long as the corresponding Atom, and will never be freed before the Atom.

Using the same solution as OpenMM does not looks good to me here, as this would need to introduce a new object type, and corresponding `create`/`free`/`count` functions, in addition to the `string_list_get` one. This is a good solution if you are expected to use a lot of these objects, which should not be the case here.

**Comment by Luthaf** [comment]
This is basically done for now =)
