### ISSUE TITLE
More matrix operation support

### ISSUE THREAD

**Issue by frodofine** [chemfiles/chemfiles#162]
While writing the GRO parser, I've come to realize there should be two features relating to `Matrix3D`.

- [x] Support for scalar operations such as `*` and `/`.

- [ ] Support for compound operators `*=`, `+=`, etc.

- [ ] Support for setting the unit cell via a matrix.

**Comment by Luthaf** [comment]
Yes, these would be nice! 

Also, while working on cfiles, I found myself missing assignment operators on both Vector3D and Matrix3D:

```
Vector3D += Vector3D
Vector3D -= Vector3D
Vector3D /= scalar
Vector3D *= scalar

# Do we want this one?
Vector3D *= Matrix3D

Matrix3D += Matrix3D
Matrix3D -= Matrix3D
Matrix3D *= Matrix3D
Matrix3D /= scalar
Matrix3D *= scalar
```

**Comment by frodofine** [comment]
Those do not look too bad to add!

**Comment by frodofine** [comment]
What is your opinion on stream operators ( `<<` in particular)?

**Comment by Luthaf** [comment]
Honestly, I don't like them, mainly because to define them you have to pull the whole `<iostream>` header in =)

What would be your use case with them ? For debug purposes I sometimes add an implementation of `operator<<` where needed and then remove it.

I think `operator>>` does not make sense here, as there is no single way to parse a Matrix/Vector from a stream (is it `(a, b, c)`? `[a, b, c]`? `a, b, c`? `a; b; c`? ...)

**Comment by frodofine** [comment]
Mostly for debugging as I use them quite a bit in my own projects for this purpose! I won't implement them then!

**Comment by Luthaf** [comment]
Yeah, it is not that hard to do whenever we need this. If a lot of people start asking for it, we could have it hidden under an un-documented  preprocessor flag.

**Comment by frodofine** [comment]
I love un-documented preprocessor flags! My current project is filled with them!
</s>
