### ISSUE TITLE
Error on PDB reading with anaconda 0.8.0 prebuilt library for linux 64 bits

### ISSUE THREAD

**Issue by pgbarletta** [chemfiles/chemfiles#168]
Found this issue when traying to read a PDB file with the Julia bindings:
![image](https://user-images.githubusercontent.com/5693483/41166475-ae0873ce-6b16-11e8-8edc-511d4e529783.png)

I then tried to compile [this](https://gist.github.com/pgbarletta/41fcfc1d8c36640fde3266069a76a69e) using the same pre-built anaconda libraries Julia was using:
```g++ piola.cpp -I/home/german/.julia/v0.6/Chemfiles/deps/usr/include /home/german/.julia/v0.6/Chemfiles/deps/usr/lib/libchemfiles.so -lnetcdf```

and got this:
```
/tmp/cc7XkS9e.o: In function `main':
as.cpp:(.text+0x90): undefined reference to `chemfiles::Trajectory::Trajectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```
So then, I moved my own library (which is a newer version) to the same location and recompiled and ran successfully:
```g++ piola.cpp -I/home/german/.julia/v0.6/Chemfiles/deps/usr/include /home/german/.julia/v0.6/Chemfiles/deps/usr/lib/libchemfiles.so.0.9.0 -lnetcdf```

So, finally, I pointed Julia to the new library by editing `deps.jl`.
```@checked_lib libchemfiles "/home/german/.julia/v0.6/Chemfiles/deps/usr/lib/libchemfiles.so.0.9.0"```

And now it works:
```
julia> using Chemfiles

julia> as = Trajectory("99999_4xcp.pdb")
Chemfiles.Trajectory(Ptr{Chemfiles.lib.CHFL_TRAJECTORY} @0x0000000002be6e60)

julia> nsteps(as)
0x0000000000000001
```
Now I wouldn't know how to take it from here.

**Comment by Luthaf** [comment]
>/tmp/cc7XkS9e.o: In function `main':
> as.cpp:(.text+0x90): undefined reference to `chemfiles::Trajectory::Trajectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> collect2: error: ld returned 1 exit status

This one might be related to a different version of the compiler/standard library. Which one did you use, and which was the command line? You would need at least `-std=c++11` in the command line. I would assume you are on Linux, right ? If so, which distribution?


> Now I wouldn't know how to take it from here.

It is great that you got it working with your own version of the code! The changes to PDB formats since 0.8.0 does not seems to be the culprit here (only #147 was added), so there might be an issue in the way the precompiled library was built. Could you share the PDB file with me so that I can give it a look?

**Comment by pgbarletta** [comment]
> which distribution?

Neon KDE 5.12 (16.04 release). If I recall correctly ```-std=c++11``` is a default flag for my *gcc* version (*6.3.0*).

> Could you share the PDB file with me so that I can give it a look?

[Here](https://gist.github.com/pgbarletta/72ea30b8b4aa2d2325103121fda74b2a). Although I should say, I've had the same problem with other pdbs.

**Comment by Luthaf** [comment]
I managed to link the conda-built library with g++ on my own system, and I get a weird segfault in string destructor. So maybe there is some kind of interaction with the standard C++ library. Which version do you have (what is the output of `strings /usr/lib/libstdc++.so.6 | grep LIBCXX`)?

**Comment by pgbarletta** [comment]
I get this:
```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```

**Comment by Luthaf** [comment]
Ok, so you got a newer version than mine. I'll continue to investigate, but I have no idea on the origin of the issue here.

Concerning the linker error, it comes from the changes in ABI after GCC 5. The library was compiled with gcc 4.8 and uses the older ABI, while your compiler is trying to use the newer ABI. [It looks like](https://stackoverflow.com/a/33395489/4692076) you can workaround this with a define:

```cpp
#define _GLIBCXX_USE_CXX11_ABI 0
#include <chemfiles.hpp>

// main ...
```

**Comment by pgbarletta** [comment]
Aaaahhhhhh, nice, thanks.
