### ISSUE TITLE
Feature request: Residue groups

### ISSUE THREAD

**Issue by frodofine** [chemfiles/chemfiles#178]
I believe there is a need for residue groups in the `Frame` class to store data such as chain IDs and other related information in Biologic systems (I'm sure other applications could benefit here, but I do not know them).  Such an implementation could look like:
```
class ResidueGroup {
    sorted_set<size_t> residue_ids_
    property_map prop_map_
public:
    set / get - property
    check if a residue is in the group
    add / residues from the group
}
```
Thoughts?

**Comment by Luthaf** [comment]
I am a bit worried about proliferation of ad-hoc structures here, with both Residue and ResidueGroup being loosely integrated with the Frame (both only store index of atoms/residues in a separated frame).

What is made available by `ResidueGroup` that could not be done with a `chain_id` string property on atoms/residues? If one need the ability to get all atoms with a given `chain_id`, maybe extending selections to work with properties would be another solution.

If there is a real need for ResidueGroup as a separated class, maybe we can re-organize the code to make the whole ResiudeGroup -> Residue -> Atom clearer. 

---

On this matter, see https://khinsen.wordpress.com/2013/04/10/lessons-from-sixteen-years-of-molecular-simulation-in-python/, at the end he says he would prefer having only Atom and Group instead of the whole Atoms, Groups, Molecules, Complexes, AminoAcidResidue, PeptideChain, and Protein. He does not go on to say why, but I would guess less types of groups make the code more general and easier to understand.

**Comment by frodofine** [comment]
I really like the selection based idea, although I would have no idea how to implement it...

**Comment by frodofine** [comment]
Yes, a selection mechanism would satisfy my needs (in my own project I build the residue group myself anyway, I was really just suggesting to move that upstream).

I could add the selector part my self as it looks easy enough, but I need to finish up some other projects before I can look at this more in detail.

**Comment by frodofine** [comment]
This issue is closed, with the above PRs.
