### ISSUE TITLE
Rewrite DCD reader from VMD molfile to our own implementation

### ISSUE THREAD

**Issue by lmiq** [chemfiles/chemfiles#370]
*Edit by @Luthaf: this was originally reported in the julia binding repository*

I noticed that if one read successive frames of a trajectory, using:

```
t = Chemfiles.Trajectory(dcd,'r')
for i in 1:nframes
    frame = Chemfiles.read(t)
end
```

the complete trajectory ends loaded into memory.

I guess that it would be useful to have a function `read!(t,frame)`, which modifies an existing `Frame` structure, such that no additional memory is required to read further frames.

Or is there any other solution? I am having trouble with calculations being Killed by running out of memory.

**Comment by lmiq** [comment]
Unfortunately there are different exact formats depending on which package generated the files. My experience is that using a record marker 4 will always work for trajectories produced by NAMD (likely the most important simulation package which uses this format now). 

But for an almost comprehensive routine to deal with this format one would need to consider all the cases, as here:

https://www.ks.uiuc.edu/Research/vmd/plugins/doxygen/dcdplugin_8c-source.html

**Comment by Luthaf** [comment]
Ok, that's unfortunate but good to know. Thanks a lot!

**Comment by Marco-Mendivil-Carboni** [comment]
> ps. The writting function does not work, in the sense that VMD cannot understand it, I do not know why.

I know this issue is closed and this may not be the best place to ask this question but how can you solve this? If you could point me to some reference on how to properly write a dcd file so that I can view it with VMD I would very much appreciate it. I haven't been able to do it looking at the documentation.

**Comment by lmiq** [comment]
No, I was never able to write that myself. I think it is better to try to write another format that is better documented, like gromacs output trajectory files, for example.

**Comment by Marco-Mendivil-Carboni** [comment]
I see, I'll try that, thanks!

**Comment by Luthaf** [comment]
So the DCD documentation is really bad, and I had to read the VMD implementation to understand what's going on. If you want to write your own DCD writer, have a look inside VMD source code (or chemfiles source code!) to see what needs to be done. Otherwise, you can also directly use chemfiles in your software! 😃
