### ISSUE TITLE
Rewrite LAMMPS trajectory reader

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#371]
We are currently using the molfiles implementation, with all the related problems, cf https://github.com/chemfiles/chemfiles/issues/154.

**Comment by ezavod** [comment]
The LAMMPS trajectory reader has another problem apart from the shortcomings mentioned in the original molfile issue: LAMMPS allows for changing particle numbers which currently crashes chemfiles. A changing number of particles can be achieved by either creating atoms between runs or by [specific fixes](https://lammps.sandia.gov/doc/fix_append_atoms.html).
<details>
<summary>Example</summary>
Input script:

```
dimension 3
boundary p p p

region box block 0 10 0 10 0 10
create_box 1 box
mass * 1.0

dump 1 all atom 1 out.lammpstrj

create_atoms 1 single 5 5 5
run 0
create_atoms 1 single 6 6 6
run 1
```
Creates the following trajectory:

```
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
1
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 1.0000000000000000e+01
0.0000000000000000e+00 1.0000000000000000e+01
0.0000000000000000e+00 1.0000000000000000e+01
ITEM: ATOMS id type xs ys zs
1 1 0.5 0.5 0.5
ITEM: TIMESTEP
1
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 1.0000000000000000e+01
0.0000000000000000e+00 1.0000000000000000e+01
0.0000000000000000e+00 1.0000000000000000e+01
ITEM: ATOMS id type xs ys zs
1 1 0.5 0.5 0.5
2 1 0.6 0.6 0.6
```
Upon reading the first frame:

```
[chemfiles] lammpsplugin) Too many atoms in timestep. 2 vs. 1

terminate called after throwing an instance of 'chemfiles::FormatError'
  what():  error while reading the file at 'out.lammpstrj' with LAMMPS plugin
```
</details>
Since it's a text format the implementation should be relatively easy but complication arises from the high flexibility. So far I found the following things to keep in mind:

- positions can be scales or not (or both or unwrapped when using `custom` style)
- atoms might not be in order
- time is optional
- triclinic boxes have a bounding box (needs additional computation to get the actual box if possible at all)
- molfile [mentions an old format](https://github.com/chemfiles/molfiles/blob/chemfiles/src/lammpsplugin.c#L18-L52)

IMHO we shouldn't deal with the `custom` format extension (at least initially). Molfile does only support the basic `atom` style anyway and additional data fields created by `custom` can be handled later (if needed).

**Comment by Luthaf** [comment]
Do you have a trajectory with variable number of atoms? That would be a great test for when we get to implement this!
