### ISSUE TITLE
Guessing the bonds using the distance-based algorithm

### ISSUE THREAD

**Issue by ynaimi** [chemfiles/chemfiles#374]
Some bonds were incorrect when I opened a PDB file presenting a slightly different (and wrong) description of amino acids. I managed to correct this behavior by using the `guess_bonds()` function in the `Frame` class but this resulted in extending the opening time since it has a quadratic complexity (two nested for loops). I was wondering why on VMD (where the code of chemfiles function `guess_bonds()` was taken from) can load the file way faster than what I observed using chemfiles and with corrects bonds. I am currently working on trying to optimize this function on chemfiles and looking at the VMD code to see how it is done on the latest release. I wanted to share this with you in case you would have a comment/idea on that.

**Comment by ynaimi** [comment]
Sorry, just found that  #358 is closely linked to this. Don't hesitate to close mine if you think it is redundant.

**Comment by Luthaf** [comment]
One thing that VMD does to make this bond guessing faster is use a [cell list algorithm](https://en.wikipedia.org/wiki/Cell_lists) to partition the atoms in the structure into cells, and then only check relevant cells for neighbors. Implementing this should yield good improvement on the bond search timing!

This is related to #116 rather than #358 (which is about changing the algorithm altogether), an octree being another possible way of speeding neighbors search, although a bit more complex to implement AFAIK.

**Comment by Luthaf** [comment]
I'll close this issue in favor of #116 =)
