### ISSUE TITLE
`Trajectory::read` fails after an exception

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#398]
Initially discovered here: https://github.com/chemfiles/chemfiles/pull/391#discussion_r589074931. Calling `Trajectory::read()` with a text format after an exception have been thrown currently fails since the file cursor is not reset at the beginning of the step.

I think the most sensible fix for this is to always increment the step counter and update the file cursor correspondingly, even when an exception is thrown. So code like this 

```cpp
auto trajectory = Trajectory("half-broken.lmp");

try {
   trajectory.read();
} catch (...) {

}

auto frame = trajectory.read();
```

gives you the second frame and ignore the broken first one. What do you think?

**Comment by ezavod** [comment]
Agree, simply advancing the file cursor anyways is the best fix. The tracking of the current step is already done in some formats e.g. the XTC format which can serve as reference. But actually advancing the cursor might be tricky for third-party libraries (like xdr_file).
Anyhow, I guess that this mostly occurs in text files since they can be easily edited or produced by some self-made script.
