### ISSUE TITLE
Lammps dump properties not found.

### ISSUE THREAD

**Issue by SamTov** [chemfiles/chemfiles#409]
I am using chemfiles to read lammps dump files as a replacement for a reader that I have written as I would like to have a generic reader that can handle many formats. Lammps is however, the most important one at the moment. I find that chemfiles returns an empty list when I call `frame.list_properties ` and returns 0 when I call `frame.properties_count`. However, if I call `frame.velocities` or `frame.positions` it does return the velocities and positions. Even the `frame.has_velocities` returns true.  

Perhaps I have misunderstood how the properties work but when looking through the cpp code I noticed that chemfiles does in fact read additional properties from the data and I believe the charges on the atoms were also stored correctly. I would like to be able to access any of the properties in the dump, including custom ones. The code appears to do this but I cannot get the api to access them.

the header of the file is:

```bash
ITEM: TIMESTEP
100
ITEM: NUMBER OF ATOMS
1600
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 3.1134167999999999e+01
0.0000000000000000e+00 3.1134167999999999e+01
0.0000000000000000e+00 3.1134167999999999e+01
ITEM: ATOMS id mol type element q x y z ix iy iz
```
I also frequently will dump forces, energy, or stresses along with the data.

My input script is quite simple.
```python
>>> from chemfiles import Trajectory

>>> data = Trajectory('test_data/dump.lammpstrj')
>>> frame = data.read()
>>> frame.nsteps
4
>>> frame.has_velocities()
True
>>> frame.list_properties()
[]
>>> frame.properties_count()
0
```

**Comment by Luthaf** [comment]
So the handling of properties is not fully consistent currently, and that's something I'd like to improve before releasing version 1.0. In particular, velocities, mass and charge have a special treatment in the code.

With the current version, frame properties are used for single scalar values associated with the frame, and atom property are used for scalar values associated with each atom. To access the velocities for example you should do 

```python
data = Trajectory('test_data/dump.lammpstrj')
frame = data.read()

frame.velocities  # give a numpy ndarray with the velocities
```

and for the mass/charges

```python
data = Trajectory('test_data/dump.lammpstrj')
frame = data.read()

for atom in frame.atoms:
    atom.mass
    atom.charge
    # also not atomic "properties"
    atom.name
    atom.type
```

> I also frequently will dump forces, energy, or stresses along with the data.

Energy should be accessible as `frame.get("energy")` in C++ or `frame["energy"]` in Python if defined as 

```
ITEM: energy
-42.55
```

I don't think stress is supported right now since it is a matrix. Do you have an example file containing the stress?

**Comment by SamTov** [comment]
I can certainly find one for you. Is this also applicable to a custom property defined by the lammps user to be dumped?

**Comment by Luthaf** [comment]
I'm not sure, maybe @ezavod knows more about this. If you can contribute a file with such user-defined property, we can add it to the test set and make sure this is supported

**Comment by SamTov** [comment]
I will speak to some of my collaborators and get some descriptive example files. The package is very helpful by the way. We want to integrate it into some software we are writing.

**Comment by ezavod** [comment]
Unfortunately chemfiles does not support any additional properties in LMAPPS dumps yet (neither per-frame nor per-atom). The only ones that are read are [type, element name, mass, and charge](https://github.com/chemfiles/chemfiles/blob/2947814504156c4b1489d9fd34e83e8dfdaf77ae/src/formats/LAMMPSAtom.cpp#L405-L510) (those have this special treatment which @Luthaf alluded to) in addition to positions and velocities.

But luckily we have already much of the underlying work for **per-atom properties** done, so that adding additional properties should be pretty straight forward. I'm actually using a simple hack to read per-atom flags for a while now:
<details>

```patch
diff --git a/src/formats/LAMMPSAtom.cpp b/src/formats/LAMMPSAtom.cpp
index c152c4b1..2159ebd9 100644
--- a/src/formats/LAMMPSAtom.cpp
+++ b/src/formats/LAMMPSAtom.cpp
@@ -354,6 +354,8 @@ void LAMMPSAtomFormat::read_next(Frame& frame) {
     }
     std::vector<lammps_atom_attr_t> fields;
     fields.reserve(atoms_item.size() - 1);
+    std::vector<std::string> field_names;
+    field_names.reserve(atoms_item.size() - 1);
     optional<size_t> atomid_column = nullopt;
     std::vector<bool> duplicate_check;
     optional<std::vector<std::array<int, 3>>> images = nullopt;
@@ -370,6 +372,7 @@ void LAMMPSAtomFormat::read_next(Frame& frame) {
             images = std::vector<std::array<int, 3>>(natoms, {0, 0, 0});
         }
         fields.push_back(attr);
+        field_names.emplace_back(atoms_item[i]);
     }
     lammps_position_representation_t use_pos_repr = detect_best_pos_representation(fields);
 
@@ -505,7 +508,9 @@ void LAMMPSAtomFormat::read_next(Frame& frame) {
                 atom.set_charge(charge);
             } break;
             case ATOMID:
+                break;
             case UNKNOWN:
+                atom.set(field_names[j], parse<double>(splitted[j]));
                 break;
             }
         }
```
</details>
I'll try to tidy this up and open a PR for this soonish.


> I don't think stress is supported right now since it is a matrix.

My understanding is that LAMMPS dumps arrays element wise. This means that a 3x3 stress matrix results in 6 separate properties that can be retrieved by something like `atom.get("c_stress[1]"); atom.get("c_stress[2]"); ...`.

While per-atom properties are rather easy, **per-frame** or global properties are not as simple. My understanding of the documentation is that LAMMPS dump does only allow for per-atom properties (["[...] the compute, fix, or variable must generate per-atom values [...]"](https://docs.lammps.org/Howto_output.html#dump)). The usual 'atoms' or 'custom' styles have a fixed header and adding an extra `ITEM: energy` would break these. However the 'local' style seems to accommodate additional header data, which might be used by chemfiles to deal with per-frame properties but I have to look at this in more detail.

Any files that show use cases are very much appreciated.

**Comment by SamTov** [comment]
Yeah we have a small python implementation of such a reader that can automatically read the typical LAMMPS dump parameters. In cases where a user has custom values we ask that they provide a dict argument to assign the columns to a property. 

In per-frame properties we have the same thing but then this must be read from a different file completely. I will be working on implementing chemfiles into my project for a few days this week and so will update the test files I am using for this implementation in the coming days. I can also take a look at some changes as well. My cpp is not great but I would like to improve.

**Comment by ezavod** [comment]
> I can also take a look at some changes as well.

Awesome, feel free to test an scrutinize #413 and see if this fulfills you needs.

> In per-frame properties we have the same thing but then this must be read from a different file completely.

My understanding is that those per-frame properties have to be dumped via the `thermo` command and cannot be part of the trajectory file itself. IMHO dealing with those extra files is not part of chemfiles. The files seem to be easily read by packages like pandas in python.

**Comment by SamTov** [comment]
> My understanding is that those per-frame properties have to be dumped via the thermo command and cannot be part of the trajectory file itself

This is true and I never read them together. Of course there can always be a python reader for this stuff as it is very customizable. We also have one of these already it just doesn't have the speed of c++.

> Awesome, feel free to test an scrutinize #413 and see if this fulfills you needs.

I will check it out today! Thanks.

**Comment by SamTov** [comment]
I see that in the cpp code you use the atom id for referencing. I have two questions there, is it possible to access this atomid? Secondly, if the atoms are not sorted, do you do anything in this case?

**Comment by ezavod** [comment]
> if the atoms are not sorted, do you do anything in this case?

Atoms are sorted according to their id, if ids are dumped. Else, the ordering of the trajectory file is used. This assumes consecutively numbered ids starting from 1. LAMMPS does not really enforce this, but I think this a de facto standard nonetheless.

> is it possible to access this atomid?

Yes, this is indirectly possible because chemfiles uses the atom ids to sort the atoms accordingly. So the i-th atom in the frame has the corresponding ID = i+1.

**Comment by SamTov** [comment]
I like the PR. I think I will have to wait for it to be merged. I actually also had some issues building the Python package locally as despite my `-e` flag it tried to save data in a protected file. Nonetheless, I can only add it to my project when the functionality is part of the main code branch so I will wait for the PR to go through.

**Comment by Luthaf** [comment]
>  I actually also had some issues building the Python package locally as despite my -e flag it tried to save data in a protected file.

Could you open a separate issue for this in https://github.com/chemfiles/chemfiles.py/?

**Comment by SamTov** [comment]
Yes I will do that soon.

**Comment by Luthaf** [comment]
Does #413 cover all your use cases @SamTov?

**Comment by SamTov** [comment]
yes I would say to. We can close this issue now.

**Comment by SamTov** [comment]
Sorry, I am still struggling to use this PR through the python api. Does something else need to be done on this end?

**Comment by Luthaf** [comment]
>  Does something else need to be done on this end?

You need to update the version of libchemfiles.so used by python. This mean either waiting for the full release (tracked in #415); or building it yourself. 

In the second case, since there were only backward compatible changes between the latest release and 0.10.1, you should be able to get it working by running:

```bash
git clone https://github.com/chemfiles/chemfiles.py/
cd chemfiles.py

# update the git submodule containing the C++ library
cd lib 
git fetch
git checkout 0.10.1
cd ..

# re-build & re-install the library
pip install .
# alternative to the pip install above, with more verbose output
# python setup.py install
```

**Comment by SamTov** [comment]
I got a
```bash
error: pathspec '0.10.1' did not match any file(s) known to git
```
error.

**Comment by Luthaf** [comment]
From the `lib` directory, what's the output of these commands? 

```
git fetch
git remote -v
git tag
```

**Comment by SamTov** [comment]
```bash
git fetch
>>>
git remote -v
>>> origin	https://github.com/chemfiles/chemfiles.py/ (fetch)
>>> origin	https://github.com/chemfiles/chemfiles.py/ (push)
git tag
>>> 0.10.0
>>> 0.4.0
>>> 0.5.0
>>> 0.6.0
>>> 0.7.1
>>> 0.7.2
>>> 0.7.3
>>> 0.7.4
>>> 0.8.0
>>> 0.9.1
>>> 0.9.2
>>> 0.9.3
```

**Comment by Luthaf** [comment]
My bad, does it work if you use `git fetch --tags`?

**Comment by SamTov** [comment]
no that also did not work. 

```bash
git fetch --tags
>>>
git checkout 0.10.1
>>> error: pathspec '0.10.1' did not match any file(s) known to git
```

**Comment by Luthaf** [comment]
You are running from inside the `lib` folder right? I missed that the output of `git remote` was wrong (should be `https://github.com/chemfiles/chemfiles/`), today have been a long day ...
 
My instructions above where missing a `git submodule update --init`, I changed them. Can you run `git submodule update --init` from chemfiles.py and then fetch/checkout from the `lib` folder?

**Comment by SamTov** [comment]
Appears to have worked!

I also see what you were trying to explain now... It was just checkout out the correct branch on the chemfiles core library then installing the python package.

I ran a test on a system with forces and it returns them correctly.
