### ISSUE TITLE
Unit change during GROMACS reading.

### ISSUE THREAD

**Issue by SamTov** [chemfiles/chemfiles#441]
When I was reading in an xtc file with a `.gro` file as a topology, despite the `.gro` file and assumedly, due to the GROMACS standards, the `.xtc` file being in nanometer units, the output from the frame reading was in Angstrom. Is this normal practice for Chemfiles?

**Comment by Luthaf** [comment]
I'm not sure I understand your question. You expected the data in the frame to be in nanometers, but you got Angstroms instead? If that's the case, that's by design. Chemfiles tries to convert everything so that data stored in a `Frame` is in Angstroms (`Angstrom/fs` for velocities), and convert to the format units (if they are defined) when reading/writing. For example, converting a .xyz to a .gro will convert from the (assumed) Angstroms in the .xyz file to nanometers.

Behavior around units is not very well documented yet, cf #397.

**Comment by SamTov** [comment]
Yep that was exactly the question. As we use the Chemfiles reader in MDSuite it is important to know the units as they are read in so we will document and enforce this in our readers.
