### ISSUE TITLE
LAMMPS Data format exporter might require a blank line

### ISSUE THREAD

**Issue by DmitriyMarin** [chemfiles/chemfiles#487]
This is not a problem, just wanted to highlight that according to the [LAMMPS Data format description](https://docs.lammps.org/2001/data_format.html) there should be more blank lines than **chemfiles** outputs. While **chemfiles** reads the written file without a problem, some other software might complain (I haven't checked).

For example, for a single atom **chemfiles** will write the following:
```
LAMMPS data file -- atom_style full -- generated by chemfiles
1 atoms
```

While the [LAMMPS Data format description](https://docs.lammps.org/2001/data_format.html) states that *Blank lines are important* and *1st 2 lines are ignored*, i.e. the line with the number of atoms should be on the 3rd line, here is the example from the above-mentioned link:
```
LAMMPS Description           (1st line of file)

100 atoms         (this must be the 3rd line, 1st 2 lines are ignored)
```

**Comment by Luthaf** [comment]
While this is the old documentation for the format, and I can't find anything similar in the modern documentation (https://docs.lammps.org/read_data.html#format-of-a-data-file only mention a single header line), it might still be worth to change this for compatibility with other old software. 

LAMMPS itself can use files produced by chemfiles with no issues since ~2016 (I used it during my PhD).

**Comment by DmitriyMarin** [comment]
Yes, this doc is quite old but might have been followed by some old software. I haven't yet met an issue with another software not being able to read a LAMMPS data file due to the missing blank line at the 2nd line, just wanted to highlight it in case there are some compatibility issues.
