### ISSUE TITLE
Implement reading gzipped/bzip/bzip2 files 

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#71]
The TextFile class is here to abstract the used interface, so hopefully this will be as easy as implementing the TextFile interface for a GZipFile class. 

https://github.com/mateidavid/zstr looks like a nice library that provides `std::fstream`-like objects to read and write files compressed with zlib.

**Comment by Luthaf** [comment]
Now that this is partly implemented, I think that we want a way to request the use of compressed files even if the file extension does not match. A simple way to do this would be to pass the compression method in the `format` argument to Trajectory constructor: `format = "LAMMPS Data/XZ"`; `format = "Tinker/GZ"`.

**Comment by frodofine** [comment]
And do a string slit on the `/` character to get compression method and `format`?

One concern I have for binary formats is one would need to know if that binary format supports reading from a compressed format or not. Since we've decided this would be implemented in a per format manner, maybe the constructor for the corresponding classes should throw an error if it detects the format is compressed. Thoughts?

**Comment by Luthaf** [comment]
Yeah, we might want to only support this for text formats for now. So maybe add another field in FormatInfo for text formats and checking on this.

**Comment by Luthaf** [comment]
Bzip2 support was added in #284, so this is done!
